name: Publish documentation

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  gh-release:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@master
      - uses: redkubes/docusaurus-deploy-action@v1
        with:
          git-user: lbhackney-automation
          git-password: ${{secrets.GITHUB_TOKEN}}
          deployment-branch: gh-pages