name: Publish documentation

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  gh-release:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@master
      - uses: redkubes/docusaurus-deploy-action@v1
        with:
          node-version: "12.x"
      - name: Release to GitHub Pages
        env:
          GIT_USER: git
        run: |
          git config --global user.email "selwyn.preston@hackney.gov.uk"
          git config --global user.name "LBHSPreston"
          if [ -e yarn.lock ]; then
          yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi
          npx docusaurus deploy
